spring:
  application:
    name: schoolsearch

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/schoolsearch
    username: NBIGLARI
    password: -kots578-
    spring.jpa.hibernate.ddl-auto: create-drop
    driverClassName: org.postgresql.Driver

  ribbon:
    ServerListRefreshInterval: 1000

  endpoints:
    health:
      sensitive: false
    restart:
      enabled: true
    shutdown:
      enabled: true

  processManagement:
        fork: true
  net:
        bindIp: 127.0.0.1
        port: 5432
  flyway:
      check-location: false
      validate-on-migrate: false
      locations: classpath:db/migration